### ISSUE TITLE
Refactor event system

### ISSUE THREAD

**Issue by DRSchlaubi** [Quillraven/Quilly-s-Adventure#15]
The current implementation needs a method for every single listener type and for every single event
this should change that you have an Event interface and then you have only one method for dispatching events

**Comment by DRSchlaubi** [comment]
#16 will not close this

**Comment by Quillraven** [comment]
I saw some people doing things like having a general `message` class that contains a `type` enum attribute to define what kind of message it is. Is this what you are aiming for?

Because if yes then I went against that on purpose because in my opinion it makes the listener code clearer if it has explicit react methods like `onCollision` or `onMapChange` where I can pass the really important stuff per parameter instead of having a `onNotify` method with a generic message that I need to check all the time about its type and then maybe cast it to the specific message to get my information out of it.

Or do you have a different approach in mind?

**Comment by Quillraven** [comment]
I also close this issue. I fully agree that the approach in this project was not the best but it worked out for version 1.
I think noone will invest the effort to rewrite the existing event handling and test everything again, so I will close it for now.

Will definitely consider that in a new project!
